name: hacker_news
description: A simple Hacker News client built in Flutter using MobX for state management.
version: 1.0.0+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^0.3.7
  flutter_mobx: ^0.3.2
  # a Hacker News API
  hnpwa_client: ^2.0.0
  # to open urls
  url_launcher: ^5.1.3

dev_dependencies:
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.4

flutter:
  uses-material-design: true
