name: slack_onboarding
description: A simple app inspired by the first page of Slack's onboarding.
version: 1.0.0+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.1.9

flutter:
  uses-material-design: true
  # assets
  assets:
   - assets/images/
