name: github_jobs
description: A simple GitHub Jobs client written in Flutter.
version: 1.0.0+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  http_client: ^1.3.1
  flutter_html: ^0.11.0
  url_launcher: ^5.1.3
  timeago: ^2.0.19

flutter:
  uses-material-design: true
