name: weather
description: A simple weather app.
version: 1.0.0+1
authors: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^2.0.1
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # app is rendered using the material design
  uses-material-design: true
  # assets used
  assets:
   - assets/images/
