name: notes
description: A simple note-taking app built in Flutter.
version: 1.0.0+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # to use sqlite
  sqflite: ^1.1.5
  # to display a staggered grid view
  flutter_staggered_grid_view: ^0.3.0

flutter:
  # rendered using material design
  uses-material-design: true
  # assets
  assets:
    - assets/database/template.db
