name: currency_converter
description: A simple currency converter build using Flutter.
version: 1.0.0+1
author: James Leahy <defuncart@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  http: ^0.12.0
  flutter_money_formatter: ^0.8.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
  # assets
  assets:
    - assets/database/currencies.json
    - assets/images/
    # - assets/mocking/
